apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-client-1-depl
  labels:
    app: test-client-1-depl
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: test-client-1
  template:
    metadata:
      labels:
        app: test-client-1
        tier: test-client-1
    spec:
      containers:
        - name: test-client-1
          image: passhag/test-client-1:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: test-client-1
---
apiVersion: v1
kind: Service
metadata:
  name: test-client-1-srv
  labels:
    app: test-client-1-srv
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: test-client-1
    tier: test-client-1
  type: LoadBalancer